channels:
- conda-forge
dependencies:
- python=3.8.8
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - pydeprecate==0.3.1
  - pytorch-lightning==1.4.3
  - scipy==1.6.1
  - torch==1.8.1
  - torchvision==0.9.1
name: mlflow-env